### ISSUE TITLE
History is broken after Reconnect

### ISSUE THREAD

**Issue by farion** [EXXETA/correomqtt#125]
**Describe the bug**
After a reconnect in a connection tab, the publish history is broken

**To Reproduce**
1. Connect to a broker
2. Publish a message
3. Disconnect
4. Connect
5. Publish another message
6. NullPointerException in History is thrown.
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.correomqtt.business.provider.PersistPublishHistoryProvider.getTopics(PersistPublishHistoryProvider.java:72)
	at org.correomqtt.business.provider.PersistPublishHistoryProvider.onPublishSucceeded(PersistPublishHistoryProvider.java:79)
	at org.correomqtt.business.dispatcher.PublishGlobalDispatcher.lambda$onPublishSuceeded$0(PublishGlobalDispatcher.java:17)
	at org.correomqtt.business.dispatcher.BaseConnectionDispatcher.lambda$triggerFiltered$2(BaseConnectionDispatcher.java:33)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.correomqtt.business.dispatcher.BaseConnectionDispatcher.triggerFiltered(BaseConnectionDispatcher.java:27)
	at org.correomqtt.business.dispatcher.PublishGlobalDispatcher.onPublishSuceeded(PublishGlobalDispatcher.java:17)
	at org.correomqtt.business.dispatcher.PublishDispatcher.onPublishSucceeded(PublishDispatcher.java:18)
	at org.correomqtt.business.services.PublishService.onSucceeded(PublishService.java:40)
	at org.correomqtt.gui.business.ServiceTask.succeeded(ServiceTask.java:26)
	at javafx.concurrent.Task.setState(Task.java:726)
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1436)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**Expected behavior**
No Exception

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Version: 0.14.2

**Comment by thagel** [comment]
This issue can't be readjusted.
