### ISSUE TITLE
Can't start application on Ubuntu 16.04

### ISSUE THREAD

**Issue by david-woelfle** [EXXETA/correomqtt#57]
Hi everyone,

I just found your project and it looks just what would my live much easier, at least when developing distributed applications with MQTT ;) I have installed the prebuild .deb package but unfortunately cannot start the application. I get the following output.
```
david@machine:~$ /opt/correomqtt/bin/CorreoMQTT 
11:01:39,891; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Application started.
11:01:39,895; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;JVM: Oracle Corporation | OpenJDK Runtime Environment | 14+36-1461.
11:01:39,896; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;CorreoMQTT version is 0.13.0.
11:01:39,897; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Setting initial correo version in settings: 0.13.0
11:01:39,898; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Locale is: en_US
11:01:39,920;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
11:01:45,889;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
11:01:45,909; INFO;4j.DefaultPluginStatusProvider;JavaFX-Launcher;               ;Enabled plugins: []
11:01:45,909; INFO;4j.DefaultPluginStatusProvider;JavaFX-Launcher;               ;Disabled plugins: []
11:01:45,911; INFO; org.pf4j.DefaultPluginManager;JavaFX-Launcher;               ;PF4J version 0.0.0 in 'deployment' mode
11:01:45,998;ERROR;yring.kwallet5.KWallet5Keyring;JavaFX-Launcher;               ;Command failed with exit code 2
Exception in Application init method
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.correomqtt.business.keyring.KeyringException
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.runShellCommand(KWallet5Keyring.java:158)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.runQDBusCommand(KWallet5Keyring.java:142)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.isEnabled(KWallet5Keyring.java:135)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.isSupported(KWallet5Keyring.java:51)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.correomqtt.business.keyring.KeyringFactory.getSupportedKeyrings(KeyringFactory.java:38)
	at org.correomqtt.business.keyring.KeyringFactory.create(KeyringFactory.java:14)
	at org.correomqtt.gui.keyring.KeyringHandler.init(KeyringHandler.java:134)
	at org.correomqtt.CorreoMqtt.init(CorreoMqtt.java:82)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
CorreoMQTT Failed to launch JVM
```
Is there anything I can do?

Thank you a lot

- David

**Comment by fisch3r** [comment]
Hi David, 

is it Ubuntu with KDE or GNOME?

**Comment by david-woelfle** [comment]
Hi Markus,
thank you for your reply! Actually none of both, it's still uses Unity. However, might be that I have some KDE components installed too.

**Comment by farion** [comment]
Hi David,

it looks like that the detection for the keyring runs into a trap. You have a Linux, but the QBus-Command failed somehow unexpected. Unfortunately there is no additional log available. I have a guess and will add more robustness here.

Maybe you can provide the output and the return code (``echo $?``) of the following command? Just run in a terminal with your user.
```
qdbus org.kde.kwalletd5 /modules/kwalletd5 isEnabled
```

**Comment by farion** [comment]
@david-woelfle 
I tried to reproduce the issue and found the reason. It seems, that if qdbus is available, but kwallet not, the qdbus command exits with 2 as in your log. I guess this is the case for your system. Unfortunately we do not catch that case during keyring detection.

I uploaded a deb file, with a fix. Maybe you can check.
https://github.com/EXXETA/correomqtt/releases/download/untagged-9700bcda67e503547820/correomqtt_0.13.0-1_amd64.deb

**Comment by david-woelfle** [comment]
@farion
Thank you for working on this! 👍
I am currently on vacation but will check the updated version once I am back in front of my laptop next week.

**Comment by fisch3r** [comment]
@farion just checked it for Ubuntu 16.04 and Ubuntu 20.04. It works now for both systems. There is only one misleading dialog appearing:
![keyring_dialog](https://user-images.githubusercontent.com/584963/91824663-66ca9700-ec3b-11ea-9423-f2955b9ceceb.png)

Steps to reproduce:
- Fresh install of Ubuntu 16.04 or Ubuntu 20.04
- Install Correo
- Start Correo

**Comment by david-woelfle** [comment]
> @david-woelfle
> I tried to reproduce the issue and found the reason. It seems, that if qdbus is available, but kwallet not, the qdbus command exits with 2 as in your log. I guess this is the case for your system. Unfortunately we do not catch that case during keyring detection.
> 
> I uploaded a deb file, with a fix. Maybe you can check.
> https://github.com/EXXETA/correomqtt/releases/download/untagged-9700bcda67e503547820/correomqtt_0.13.0-1_amd64.deb

Hi everyone, I tried to check, but get a 404 when clicking on that link. I instead tried the latest .deb file from the release page (https://github.com/EXXETA/correomqtt/releases/download/v0.13.0/correomqtt_0.13.0-1_amd64.deb) but that throws the same error again:

```david@machine:~$ /opt/correomqtt/bin/CorreoMQTT
09:33:00,903; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Application started.
09:33:00,907; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;JVM: Oracle Corporation | OpenJDK Runtime Environment | 14+36-1461.
09:33:00,909; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;CorreoMQTT version is 0.13.0.
09:33:00,910; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Setting initial correo version in settings: 0.13.0
09:33:00,910; INFO;     org.correomqtt.CorreoMqtt;JavaFX-Launcher;               ;Locale is: en_US
09:33:00,930;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:02,800;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:02,833; INFO;4j.DefaultPluginStatusProvider;JavaFX-Launcher;               ;Enabled plugins: []
09:33:02,833; INFO;4j.DefaultPluginStatusProvider;JavaFX-Launcher;               ;Disabled plugins: []
09:33:02,836; INFO; org.pf4j.DefaultPluginManager;JavaFX-Launcher;               ;PF4J version 0.0.0 in 'deployment' mode
09:33:02,888;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:02,926; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'farion-theme-pack-plugin@0.0.3' resolved
09:33:02,927; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'xml-xsd-validator-plugin@0.0.2' resolved
09:33:02,928; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'json-format-plugin@0.0.2' resolved
09:33:02,928; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'xml-format-plugin@0.0.2' resolved
09:33:02,928; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'zip-manipulator-plugin@0.0.2' resolved
09:33:02,929; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'save-manipulator-plugin@0.0.2' resolved
09:33:02,935; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'base64-plugin@0.0.2' resolved
09:33:02,935; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'advanced-validator-plugin@0.0.2' resolved
09:33:02,936; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Plugin 'contains-string-validator-plugin@0.0.2' resolved
09:33:02,936;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:02,939; INFO;correomqtt.plugin.PluginSystem;JavaFX-Launcher;               ;Start Plugin Update
09:33:04,248; INFO;correomqtt.plugin.PluginSystem;JavaFX-Launcher;               ;No updates found
09:33:04,249; INFO;correomqtt.plugin.PluginSystem;JavaFX-Launcher;               ;No available plugins found
09:33:04,249;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:04,249; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'farion-theme-pack-plugin@0.0.3'
09:33:04,250; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'xml-xsd-validator-plugin@0.0.2'
09:33:04,274; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'json-format-plugin@0.0.2'
09:33:04,276; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'xml-format-plugin@0.0.2'
09:33:04,277; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'zip-manipulator-plugin@0.0.2'
09:33:04,277; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'save-manipulator-plugin@0.0.2'
09:33:04,280; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'base64-plugin@0.0.2'
09:33:04,281; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'advanced-validator-plugin@0.0.2'
09:33:04,281; INFO;org.pf4j.AbstractPluginManager;JavaFX-Launcher;               ;Start plugin 'contains-string-validator-plugin@0.0.2'
09:33:04,641; INFO;tt.business.utils.VersionUtils;JavaFX-Launcher;               ;Version is up to date or newer!
09:33:04,641;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
09:33:04,718;ERROR;yring.kwallet5.KWallet5Keyring;JavaFX-Launcher;               ;Command failed with exit code 2
Exception in Application init method
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.correomqtt.business.keyring.KeyringException
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.runShellCommand(KWallet5Keyring.java:158)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.runQDBusCommand(KWallet5Keyring.java:142)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.isEnabled(KWallet5Keyring.java:135)
	at org.correomqtt.business.keyring.kwallet5.KWallet5Keyring.isSupported(KWallet5Keyring.java:51)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.correomqtt.business.keyring.KeyringFactory.getSupportedKeyrings(KeyringFactory.java:38)
	at org.correomqtt.business.keyring.KeyringFactory.create(KeyringFactory.java:14)
	at org.correomqtt.gui.keyring.KeyringHandler.init(KeyringHandler.java:134)
	at org.correomqtt.CorreoMqtt.init(CorreoMqtt.java:82)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
CorreoMQTT Failed to launch JVM
```

**Comment by farion** [comment]
@david-woelfle Is it still a problem? Or does it work with 0.14?

**Comment by david-woelfle** [comment]
Thanks @farion looking after this issue.

As Ubuntu 16.04 has reached end of life two years ago I consider this issue solved by progress of the Ubuntu developers ;)
