### ISSUE TITLE
Crash on startup using OSX (Big Sur)

### ISSUE THREAD

**Issue by dtmohr** [EXXETA/correomqtt#81]
After upgrading to Big Sur, Correo starts crashing during startup with the following stacktrace

`09:46:55,801;ERROR;osxkeychain.OSXKeychainKeyring;JavaFX-Launcher;               ;Failed to retrieve password from osx keychain.net.east301.keyring.BackendNotSupportedException: Failed to load native library
	at net.east301.keyring.osx.NativeLibraryManager.loadNativeLibraries(NativeLibraryManager.java:26)
	at net.east301.keyring.osx.OSXKeychainBackend.setup(OSXKeychainBackend.java:24)
	at org.correomqtt.business.keyring.osxkeychain.OSXKeychainKeyring.getPassword(OSXKeychainKeyring.java:29)
	at org.correomqtt.gui.keyring.KeyringHandler.getMasterPassword(KeyringHandler.java:89)
	at org.correomqtt.gui.keyring.KeyringHandler.retryWithMasterPassword(KeyringHandler.java:113)
	at org.correomqtt.CorreoMqtt.init(CorreoMqtt.java:84)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by staxDB** [comment]
Same here..

```bash
10:26:42,984;DEBUG;tcher.BaseConnectionDispatcher;JavaFX-Launcher;               ;Trigger: PreloadingDispatcher.onProgress:19
10:26:43,063;ERROR;osxkeychain.OSXKeychainKeyring;JavaFX-Launcher;               ;Failed to retrieve password from osx keychain.net.east301.keyring.BackendNotSupportedException: Failed to load native library
	at net.east301.keyring.osx.NativeLibraryManager.loadNativeLibraries(NativeLibraryManager.java:26)
	at net.east301.keyring.osx.OSXKeychainBackend.setup(OSXKeychainBackend.java:24)
	at org.correomqtt.business.keyring.osxkeychain.OSXKeychainKeyring.getPassword(OSXKeychainKeyring.java:29)
	at org.correomqtt.gui.keyring.KeyringHandler.getMasterPassword(KeyringHandler.java:89)
	at org.correomqtt.gui.keyring.KeyringHandler.retryWithMasterPassword(KeyringHandler.java:113)
	at org.correomqtt.CorreoMqtt.init(CorreoMqtt.java:84)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)

Exception in Application init method
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)
Java has been detached already, but someone is still trying to use it at -[GlassViewDelegate dealloc]:/Users/jenkins/workspace/OpenJFX-mac/modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m:198
Caused by: org.correomqtt.business.keyring.KeyringException
	at org.correomqtt.business.keyring.osxkeychain.OSXKeychainKeyring.getPassword(OSXKeychainKeyring.java:35)
	at org.correomqtt.gui.keyring.KeyringHandler.getMasterPassword(KeyringHandler.java:89)
	at org.correomqtt.gui.keyring.KeyringHandler.retryWithMasterPassword(KeyringHandler.java:113)
	at org.correomqtt.CorreoMqtt.init(CorreoMqtt.java:84)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
```

**Comment by farion** [comment]
@dtmohr @staxDB 
Sorry, this is already fixed, but not released :/

I triggered the release of 0.14.2, but travis-ci.org does not work anymore and we have to migrate to travis-ci.com first for release builds. So either you'll wait for the migration (hopefully it won't last too long) or you'll run the code yourself from the tag.

**Comment by farion** [comment]
@dtmohr  @staxDB 
As migration to travis-ci.com has some obstacles, I decided to switch to github actions. This is now working and the release for 0.14.2 was made.

Please find the new version for MacOS here: https://github.com/EXXETA/correomqtt/releases/download/v0.14.2/CorreoMQTT-0.14.2.dmg

I would appreciate feedback if the issue is gone.

**Comment by staxDB** [comment]
Works as usual again with version 0.14.2 and MacOS Big Sur 11.6! Thanks a lot @farion!
